version: '3.4'

services:
  diplomasolution:
    image: diplomasolution:latest
    build:
      context: .
      dockerfile: DiplomaBuild.df

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MedicalDb
    ports:
      - "3309:3306"
