version: '3.4'

services:
  diplomasolution:
    restart: always
    container_name: diplomabe
    build:
      context: .
      dockerfile: DiplomaBuild.df
    environment:
      VIRTUAL_HOST: blog.DOMAIN.TLD
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "51736:80"

  diploma-sql:
    image: mysql:8.0.17
    container_name: diplomasql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MedicalDb
    volumes:
      - diplomasqlvolume:/var/lib/mysql

  nginx-proxy:
      image: jwilder/nginx-proxy
      container_name: nginx-proxy
      restart: always
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  diplomasqlvolume:

networks:
  nginx_demo:

networks:
  default:
    external:
      name: nginx_demo
